### ISSUE TITLE
Update redirect link on w3c org 1.1 spec URL

### ISSUE THREAD

**Issue by jsantell** [immersive-web/webxr#306]
The URL is broken for the link in the repo move it looks like: https://w3c.github.io/webvr/spec/1.1/ -- redirects to https://example.com/spec/1.1

**Comment by toji** [comment]
This should be fixed now.

**Comment by jsantell** [comment]
Still doesn't seem to be redirecting correctly, going to example.com

```
curl https://w3c.github.io/webvr/spec/1.1/
<!doctype html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="0; url=https://example.com/spec/1.1/">
<title>Moved…</title>
</head>
<body onload='function() { location.href = "https://example.com/spec/1.1/" + location.hash; }'>
<p>Moved to
<a href="https://example.com/spec/1.1/">https://example.com/spec/1.1/</a>
</body>
```

**Comment by cvan** [comment]
Because the repo was transferred, GitHub adds redirects, but not GitHub Pages _path_ redirects (to my knowledge); only the `https://<user>.github.io/<repo>/` path gets redirected.

If we create a temporary repo at https://github.com/w3c/webvr, we could populate that repo with just a bunch of redirect `index.html` files (or a catch-all `404.html` page) that redirects to the proper `https://<user>.github.io/<repo>/<path><queryString>`.

That unfortunately would break GitHub's server-side redirects for https://github.com/w3c/webvr -> https://github.com/immersive-web/webxr, which I think is immensely helpful (especially during this transition).

I'm not _entirely_ sure, but I _think_ this should work …

1. temporarily create a repo under https://github.com/w3c/webvr
2. create a `404.html` for catching and handling the redirects
3. publish the `master` branch to GitHub Pages (from Settings)
4. GitHub Pages gets updated so the `https://w3c.github.io/webvr/*` paths are fixed
5. delete the https://github.com/w3c/webvr repo
6. if all goes as expected, all the the https://github.com/w3c/webvr -> https://github.com/immersive-web/webxr and https://w3c.github.io/webvr/ -> https://immsersive-web.github.io/webxr/ redirects work as they did before (after the repo transfer)

This is a bit scary to me as I haven't done this exact process before, but I think it should work. (I could test it on some dummy repos and orgs, and replicate the org-transfer, repo creation, etc. process.) We might want to contact [GitHub Support](https://github.com/support) to see if perhaps they can add server-side redirects for our use case here. (I've had luck getting them solve similar one-off problems such as this one.)

**Comment by NellWaliczek** [comment]
This issue was moved to immersive-web/administrivia#14
