### ISSUE TITLE
Clarify assumptions about stationary reference space movement

### ISSUE THREAD

**Issue by klausw** [immersive-web/webxr#579]
Currently, the spec says: 

> An {{XRStationaryReferenceSpace}} represents a tracking space that the user is not expected to move around within. Tracking in a {{stationary}} reference space is optimized for the assumption that the user will not move much beyond their starting point, if at all.

I think this can be problematic since a 6DoF system will still report substantial movement even though the application has requested a stationary reference space.

This reference space should be interpreted as not *requiring* the user to move significantly from their starting position, but the application still needs to be able to handle such movement when it happens, and it must not assume that the user's position will always be essentially equivalent to their starting point position.

For example, the user may well take a couple of steps in the real world to take a closer look at a virtual object, and then remain standing in that position while using teleport or other locomotion to move around the game world. If a teleport mechanic is intended to put the user's feet in a new location, the application must adjust for the current displacement when calculating the new originOffset. (See https://github.com/immersive-web/webxr/issues/477 for more discussion of this.) If the application just places the new origin at a clicked-on floor location, the user's feet will be in the wrong place in the virtual world.

Similarly, if a game features NPC enemies that attack the player, it's essential that they aim at the displaced position and not at the origin. (IIRC Skyrim VR had that issue in early builds, where the player thought they were in cover, but were actually getting hit by enemies striking at the empty space around the origin.)

A separate issue is that the user agent doesn't enforce any restrictions on the user's pose displacement. If an application needs to prevent unexpected view positions from movement to avoid immersion-breaking behavior such as looking through walls or into objects, it needs to take its own measures such as fading or blurring the rendered view when the user is too far from the origin.

Overall, I think the distinction should be that an application should request a bounded reference space only when it has a way to make use of the bounds, for example by placing virtual objects within matching bounds in the virtual world so that they are reachable without artificial locomotion. An application that doesn't make use of that should feel free to use a stationary reference frame, but in any case needs to be able to deal with user position displacements in the range of a few meters as the user moves around.

**Comment by cwilso** [comment]
Should be fixed by the fix for #597

**Comment by klausw** [comment]
The clarification in #597 is useful, but I think it doesn't really resolve this issue. I think there are several things going on here:

* how are stationary reference types and their origins defined? (#597 does address this)
* what assumptions can applications make about user movement? For example, should a "stationary/floor-level" mode app work correctly for a user moving around a few steps in a roomscale tracked volume?
* are there expectations on the UA to apply restrictions, and what do those look like? For example, should reference spaces other than "unbounded" specifically prevent movement larger than roomscale?

**Comment by thetuvix** [comment]
Putting on my "app developer hat", my mental model for the difference between "floor-level" and "bounded" is how much the system promises me about what the user can accomplish, rather than me requiring the system to be in any particular tracking mode:
* When I've made a "floor-level" space, I know that Y=0 will be on the floor.  I'm not promised that the user has anywhere to move around in their environment, so I shouldn't build a room-scale experience that relies on that.  However, if they do move around somewhat, I'll get that position data as part of my viewer poses (as is the case with any reference space), so I should be ready to accept that.  This is sufficient for me to build a **standing experience**.
* When I've made a "bounded" space, I know that Y=0 will be on the floor, **_and_** that the user has some reasonable amount of space to walk around.  If that space is still smaller than I need, I can implement teleporting, but this should generally be sufficient for me to build a **room-scale experience**.

In that sense, "bounded" simply promises me a superset of what "floor-level" promises me.

The primary reason that we bother to make those two reference spaces separate here is that for a "bounded" experience, the system may have a defined XZ rectangle "over there" that the user needs to walk to to reach the origin, whereas for a stationary "floor-level" experience, the user might as well just stay where they are.  Therefore, the origin of "floor-level" and "bounded" can differ.  However, their tracking behavior when users do walk relative to their origins should be identical.

**Comment by thetuvix** [comment]
https://github.com/immersive-web/webxr/issues/633#issuecomment-490703457 talks through some possible reference space renames that might help the app-developer mental model above click even more.

With that, developers would be choosing between the "local-floor" reference space and the "bounded-floor" reference space, helping developers choose if they care more about the user staying locally where they're sitting/standing, or more about having some bounded amount of space in which the user can actually walk around.

**Comment by NellWaliczek** [comment]
@klausw Does #640 address your concern?

**Comment by klausw** [comment]
@NellWaliczek I think #640 does help reduce confusion, especially since "local" doesn't imply "staying at the origin" as strongly as "stationary" did. 

I added some additional clarifications in PR #648, do you think this would be appropriate to add?

**Comment by toji** [comment]
Now that #640 and #648 have landed, I think it's safe to call this one done. Thanks all!
